### ISSUE TITLE
`playlist-append` unbound

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#19]

**Comment by LeifAndersen** [comment]
Yes. Please use `append` and traditional lists for now.

In principle, I'm happy to make `playlist-append`, but I really don't want to do that for every list operation...especially when Racket lists _are_ playlists.

Although if you want, I still can certainly do playlist-append specifically. Do you want that?

**Comment by stchang** [comment]
No, I dont feel strongly either way. I do think the examples in the paper (which currently use `playlist-append`) should work though. Modifying the paper's code to use `append` would be ok as well.

**Comment by LeifAndersen** [comment]
okay, after thinking about it a bit more, I think adding `playlist-append`
does make sense, so I'll add it to video/lib. (unless you think it should
be in video/base)


~Leif Andersen

**Comment by LeifAndersen** [comment]
Okay, added.

**Comment by stchang** [comment]
Actually, I thought about it too. Is `playlist-append` what we want? It seems that a "producer append" would be more useful, since we dont really want to treat playlists specially.

But does `playlist` already do what a producer-append would do? For example, is there a functional difference between `(playlist playlist1 playlist2)` and `(playlist-append playlist1 playlist2)`?

**Comment by LeifAndersen** [comment]
uhhh...given that everything gets flattened out in the end I think you are right. Give me a minute to think about it.

**Comment by LeifAndersen** [comment]
Okay, so far after thinking about it, I think there _are_ differences, but
such that I think playliste-append should just not exist. I'll talk to you
about it tomorrow in person.


~Leif Andersen

**Comment by LeifAndersen** [comment]
Okay, playlist-append has just been removed. I'll update the prose in the paper.
