### ISSUE TITLE
`"length"` property not working?

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#22]
The following program

```racket
#lang video
(image circ.png #:length (/ (get-property blue-clip "length") 8))
(define blue-clip (color "blue" #:length 8))
```

produces the following error:

```
/: contract violation
  expected: number?
  given: "15000"
  argument position: 1st
  other arguments...:
   8
```

The result should be 8? And it should be a number (not string)?

**Comment by stchang** [comment]
Here's some more weird behavior, in case it helps.

```racket
#lang video
(define g1 (color "green" #:length 1))
(displayln (get-property g1 "length" 'int)) ; => expect 1, prints 15000
(define b8 (color "blue" #:length 8))
(displayln (get-property b8 "length" 'int)) ; => expect 8, prints 15000
(define p1 (playlist g1 b8))
(displayln (get-property p1 "length" 'int)) ; => expect 9, prints 11???
```

**Comment by LeifAndersen** [comment]
oey, that certainly is very odd.

**Comment by LeifAndersen** [comment]
Okay, looking at this a bit more, libmlt does not set any internal properties for `color`, like it does for `clip` and `image`....very odd. Anyway, I'll just set it on the Racket end to be consistent.

As for the default that is getting returned, I'm not entirely sure what is happening here. The libmlt documentation is....less than helpful here.

**Comment by LeifAndersen** [comment]
Commit b1ac9208a51680b173bfe9df385dd3436c8fb083 should fix this.
