### ISSUE TITLE
local `define`s must appear first?

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#28]
This example from the paper does not work:

```racket
; Add conference logos to the front and end of a video.
; Producer - > Producer
(define (make-talk-video main-talk)
  (playlist begin-clip
            (fade-transition 200)
            main-talk
            (fade-transition 200)
            end-clip)
  (define begin-clip (image logo #:length 500))
  (define end-clip (image logo #:length 500)))
; => begin (possibly implicit): no expression after a sequence of internal definitions
```

**Comment by LeifAndersen** [comment]
Oh ya...I need to update that.

The where macro was added much later, and I never bothered to bring it into the #lang. Do you think it should actually have it? I kind of think it loos a 'little' out of place now, but I could go either way. What do you think?

**Comment by stchang** [comment]
I didnt really like the `where`.

**Comment by LeifAndersen** [comment]
ya, it looks like we're just going to have define's semantics here for now. I guess in the future it might be interesting to add another form, like (make-video ...) that has these semantics, but not yet.

Thanks.

**Comment by LeifAndersen** [comment]
I'm reopening this as an issue for now. Perhaps we should use a binding syntax besides just define?

**Comment by LeifAndersen** [comment]
This issue is now resolved, using the lambda/video form.

We should probably come up with a better name for that though.
