### ISSUE TITLE
`project-filter` and `envelope-filter` unbound

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#29]

**Comment by LeifAndersen** [comment]
Ah, ya. `project-filter` should be `cut-filter`, as I think that makes a little more sense. Although honestly, its not so much a filter, as it should just be a function: `cut-clip` or something like that. I'll add that.

As for `envelope-filter`, good point, I will add that.

**Comment by LeifAndersen** [comment]
Okay, commit 14e9d5dbde3ed828e90e35754808ddc40b53f307 adds `cut-video`, which is basically `project-filter`. Still working on `envelope-filter`

**Comment by LeifAndersen** [comment]
Commit 10b04c95feec95091c20d0572a494289a81a6c3e fixed this.
