### ISSUE TITLE
`clip` `"length"` prop still wrong?

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#32]
```racket
(displayln
 (get-property
  (clip vid-mp4 #:start 0 #:end 2)
 "length" 'int))
; => 139
```

**Comment by stchang** [comment]
Interestingly, this is ok:
```racket
(displayln
 (get-property
  (playlist
  (clip vid-mp4 #:start 0 #:end 2))
 "length" 'int))
; => 3
```

**Comment by LeifAndersen** [comment]
This is very odd.....I blame libmlt. I guess we can just call it on our end.

Also, I presume we are going to say length = end-start+1.

Thanks.

**Comment by stchang** [comment]
`end - start` is more intuitive to me but I don't feel strongly. Just choose one

**Comment by LeifAndersen** [comment]
ya, just going with what libmlt is for now. So its end-start+1. Kind of
icky, but oh well. :(


~Leif Andersen

**Comment by LeifAndersen** [comment]
Okay, supposedly 65fbb78f7e09b190684308220c424ec2d6caf128 should fix this. Haven't tested it yet other than that the current tests still run.

**Comment by stchang** [comment]
Fine with me.

Here's another weird example (negative length):

```racket
(producer-length (color "green" #:length 1)) ; => -1 (ie, contract err)
```

**Comment by LeifAndersen** [comment]
oh right, that's my fault...

If length is negative it should be #f. Which is to say its not cut.


~Leif Andersen

**Comment by stchang** [comment]
But the above example should have length `1`, not `#f`?

**Comment by LeifAndersen** [comment]
err,,, right. Yes, this was because I had the start and end mxied up in the
length function call. If you pull it should be okay now.


~Leif Andersen

**Comment by stchang** [comment]
Now this is wrong:

```racket
(displayln (producer-length (color "green"))) ; => 1
```

**Comment by stchang** [comment]
consolidating all the length problems here:

```racket
(producer-length (color "green")) ; expected #f, got 1

;; this one is probably an end-start+1 issue?
(producer-length (multitrack (color "blue") #:length 5)) ; => expected 5, got 6
```

**Comment by LeifAndersen** [comment]
Okay. This problem 'seems' to be solved now. If its back, please open up another PR.

Thank you again. :)
