### ISSUE TITLE
`get-property` length on playlist sometimes produced `libmlt` err

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#33]
may be related to #32, not sure

```racket
 (get-property
 (playlist
  (image circ-png #:length 2)
  (fade-transition #:length 1)
  (color "blue" #:length 2)
  (fade-transition #:length 2)
  (clip vid-mp4 #:start 0 #:end 2))
"length" 'int)
; => MLT: Function mlt-playlist-mix failed
```

**Comment by stchang** [comment]
Strangely, the error only occurs when trying to retrieve the length property. Constructing the playlist by itself does not trigger the error

**Comment by LeifAndersen** [comment]
This issue seems fixed.

I should note that those specific numbers will currently fail. This is due to a bug in libmlt that I have reported and has now been fixed. But currently you need nightlies to use it.
