### ISSUE TITLE
does private/mlt.rkt need to require racket/gui/base?

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#38]
Does `private/mlt.rkt` need to require `racket/gui/base`? It seems like it might not and if so can we delete it? Including `racket/gui/base` is generally very annoying and should be avoided if it's not needed.

**Comment by LeifAndersen** [comment]
As per the conversation we had earlier, yes it does.

However, if there is a way of loading it only at runtime, that would be 100% fine. Its only needed when the libmlt functions are actually going to be rendering libmlt.

**Comment by LeifAndersen** [comment]
Okay, 4fa8d47081790d4f0a9d988127e5c7ce47f12bb0 *should* fix this.
