### ISSUE TITLE
`property-ref` unbound

### ISSUE THREAD

**Issue by stchang** [LeifAndersen/racket-video#6]
```racket
#lang video
(define g (color "green" #:length 1))
(property-ref g 'length)
; property-ref: unbound identifier in module in: property-ref
```

**Comment by LeifAndersen** [comment]
Oh right, this is currently in core, but should be in base, thank you.

**Comment by LeifAndersen** [comment]
Commits 4e982b5d34c430eb3d52671bba74f80f2fe4b926 and cf12e2dbd60ee17bd72c5165aea347fb05115f01 take care of this.

**Comment by LeifAndersen** [comment]
I should note that the function is get-property, not property-ref.

Although I'm okay with either function name, but if we do go for property-ref, I think it should probably properties-ref.

**Comment by stchang** [comment]
`get-property` is fine, just update the paper

**Comment by LeifAndersen** [comment]
That's already what the paper had iirc. (At least in the example I was
looking at.) Anyway, thanks.


~Leif Andersen

**Comment by stchang** [comment]
Ah ok nice. Fig1 still uses `property-ref`

**Comment by LeifAndersen** [comment]
oops, good catch, thanks.


~Leif Andersen
